version: "2"

services:
    
    db:
        image: postgres
        restart: always
        hostname: postgres
        container_name: db
        environment:
          POSTGRES_PASSWORD: SYXDOMS1ILVERl
        ports: 
            - 5432:5432
        volumes: 
            - {YOUR_PATH}:/var/lib/postgresql/data
             #link for gitea postgresql host.docker.internal:5432
    gitea:
        image: "gitea/gitea:latest"
        hostname: repository
        container_name: repository
        volumes:
            - {YOUR_PATH}:/data
        ports:
            - "30001:20"
            - "30000:3000"
        depends_on:
            - "db"
        #root